extends Node

const INITIAL_DIFFICULTY = Data.SHIPMENT.GEMS

const CITY_WAVE_VAL = 14
const DIFFICULTY_WAVE_VAL = CITY_WAVE_VAL

const SQUAD_SPAWN_INTERVAL:=2

const TIER_COST = 5

const WAVE_INFO := {
	START_DELAY=5,
	INTERVAL=15,
	TIME_WITH_LAST_WAVE=-5,
}
